### ISSUE TITLE
Capacitor

### ISSUE THREAD

**Issue by Linknpay** [samzilverberg/cordova-mixpanel-plugin#122]
Hello,

Are you going to create a Capacitor mixpanel plugin one day ?

Thank you

**Comment by samzilverberg** [comment]
nope, because I don't know a thing about Capacitor.
but from a very short google search and read I see that capacitor should work with corodova plugins.

this plugin is not listed as incompatible
https://capacitorjs.com/docs/plugins/cordova#known-incompatible-plugins

so try it out, maybe it just works?
