### ISSUE TITLE
Mixpanel is not being added to the window object in browser

### ISSUE THREAD

**Issue by gabalicious** [samzilverberg/cordova-mixpanel-plugin#28]
I'm using this plugin with Ionic  and I am getting a mixpanel as undefined error.  How do you think I can fix this?  I am using ionic version 1.7.15 and cordova version 6.1.1.  It works on emulator and device but not when you run ionic serve.

**Comment by samzilverberg** [comment]
as far as i know: 
ionic serve = run in browser = only cordova plugins that support "browser" platform are available.

this plugin supports "browser" plugin BUT its a pretty raw untested feature.
I took a quick look at it and it might be that mixpanel is available under window.Mixpanel when running ionic serve.

anyway, its better not count on plugins being available when running ionic serve.
I mock them for your local serving/testing and then test again on emulator/real device.

**Comment by gabalicious** [comment]
I'm getting Mixpanel is undefined even if I try window.Mixpanel.  See screenshot
<img width="351" alt="screen shot 2016-06-21 at 12 00 41 pm" src="https://cloud.githubusercontent.com/assets/241617/16236895/f46aa066-37a7-11e6-8037-74fa87bee319.png">

**Comment by samzilverberg** [comment]
I googled some and not-surprisingly found out that ```ionic serve``` doesn't support plugins. 
it just serves the assets (html, js, css) so its good for testing out layout, not plugins.

if you want to test layout with ionic serve but failing because code usage of plugins then it is advised "mock" the plugins in the window.
https://github.com/driftyco/ionic-cli/issues/354
https://www.thepolyglotdeveloper.com/2016/02/why-you-should-not-use-ionic-serve-for-hybrid-apps/

if you insist that you need to test the browser platform of plugins then this is possible via cordova:
```cordova run browser```
https://www.raymondcamden.com/2016/03/22/the-cordova-browser-platform/

**Comment by gabalicious** [comment]
Ahhh good to know.  Thanks!

We silenced the errors by doing this.

                window.mixpanel = window.console;
                window.mixpanel.track = window.console.log;
                window.mixpanel.identity = window.console.log;
