### ISSUE TITLE
Wrong params on init funcion

### ISSUE THREAD

**Issue by ZiFFeL1992** [samzilverberg/cordova-mixpanel-plugin#33]
The init function params doesn't match the JS specification as you can see in the following link:
https://mixpanel.com/help/reference/javascript-full-api-reference

`window.mixpanel.init(MIXPANEL_APIKEY, null, 'app-name');` works!

But I think we should modify the interfaces and review the documentation, also the link should be visible from our readme.md as is much rich and easy to understand.

**Comment by samzilverberg** [comment]
the plugin unifies the apis of the android & ios mixpanel libs.
so the init params matches what the above expects: just api token.

The JS lib has this different init params because it has a multi-instance (by named app) feature.
there was a request to mimic this kind of behaviour in the plugin (see #27) but i'm a little tight on time to implement it in the near future.

anyway the correct documentation to look at would be:
https://mixpanel.com/help/reference/android
https://mixpanel.com/help/reference/ios

i agree adding links to this in README would be helpful 👍

**Comment by samzilverberg** [comment]
@ZiFFeL1992 any comment from your side? i'll close the issue in a while if not.

**Comment by ZiFFeL1992** [comment]
Opps, I'm closing it! Thanks.
