### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by lay-z** [samzilverberg/cordova-mixpanel-plugin#49]
Hello! 

Apologies if this has already been answered else where (or if it is a stupid one!) but this thing has me stumped.

I keep getting this issue
Failed to load resource: net::ERR_FILE_NOT_FOUND file://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js

This file: mixpanel-jslib-snippet.js references this `//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js`

This file does exists here http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js

I've tried modifying the jslib-snippet.js so it points to a http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js

but this results in a ERR_CONNECTION_REFUSED

How can i reference the local version of mixpanel.min.js I am stumped

Thank you

**Comment by samzilverberg** [comment]
I'm a little confused as what your'e trying to achieve and what platform your'e using.
are you using browser platform??

regarding your errors
`file://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js` results in ERR_FILE_NOT_FOUND because there is probably no directory structure to match "cdn.mxpnl.com/libs" from wherever its looking from.

`http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js` resulting in ERR_CONNECTION_REFUSED can be caused by many reasons. I'll need some more info on what your'e running the code on to be able to help.

**Comment by lay-z** [comment]
Ah Yes, I am building a ionic application. Running on android/iOS. 
The errors come up when i build and run on android device.

**Comment by samzilverberg** [comment]
`mixpanel-jslib-snippet.js` is not a part of the android platform so I don't see any reason you would get an error related to it when running on android.

how are you building/running on android?

I googled a little and found this:
https://forum.ionicframework.com/t/solved-ionic-emulate-android-err-connection-refused-localhost-8100/53518

maybe its your issue?

**Comment by lay-z** [comment]
Yea i was kinda confused over why the error was coming from mix-panel-jslib-snippet.js
I might have been naughty and installed mixpanel via bower at some point before.

Have uninstalled via bower. Am now resetting ionic plugins. Lets pray.

If not looks like i'll have to whitelist the cdn.mixpanel.com url :(

**Comment by lay-z** [comment]
After remove angular-mixpanel from bower. I get an error with angular. 
It appears that i'm using angular-mixpanel.
