### ISSUE TITLE
Add windows 10 uwp platform

### ISSUE THREAD

**Issue by mobidev111** [samzilverberg/cordova-mixpanel-plugin#64]
Add support for windows 10 uwp - especially offline support

There are some existing repos that can serve as starting point:
https://github.com/canderso/Mixpanel/ (including offline support)
https://github.com/lucianojss/mixpanel-uwp/tree/master/mixpanel-uwp

**Comment by samzilverberg** [comment]
i can't see **me** doing this because of 2 major probs:

### no official mixpanel support: 

https://mixpanel.com/help/reference/ => windows phones not there...
https://github.com/mixpanel =>. again, can't find any windows sdk

### I don't have the right tool for the job

I'm using a mac and getting a windows phone dev env on it is doable but is a bitch.
i found some guides explaining how to setup a VM, so actually the dev env is on windows running in a vm...
I don't have a windows 8 (or 10) copy so anyway not doable atm.

and that is the biggest problem, _i dont wanna write code i cannot verify is working._


if you or anyone wants to implement this & test it i'll gladly accept a PR!


p.s.
those links you posted are a nice starting point! its sad that they are not updated regulary.
