### ISSUE TITLE
library not found for -lMixpanel-AppExtension

### ISSUE THREAD

**Issue by jcDu** [samzilverberg/cordova-mixpanel-plugin#74]
When I do a iOS build through ionic cloud( ionic package build ), I got this error, 'library not found for -lMixpanel-AppExtension'.
Anyone has any idea here?

**Comment by nathan5x** [comment]
You may want to follow this thread
https://github.com/samzilverberg/cordova-mixpanel-plugin/issues/69

**Comment by VictorSnow** [comment]
i am still facing this problem

npm: 4.2.0
ionic: 3.9.2
node: 8.4.0

need to manually add libMaxpanel-Appextension.a to link library to build ios app
is there any way to fix this ?

**Comment by samzilverberg** [comment]
@VictorSnow  able to solve it yet?

i have 0 experience with cordova related cloud builds so don't think i can help you.

what i did notice however, is that ever since i switched to using cocoapods (`pod`) to manage the ios lib dependency there are increasingly more probs related to it.
I plan to revert to including the lib code in a more manual way and release a new version soon.
this should definitely solve your prob.

in the meanwhile you can use an older version 2.3.5
its stable, has older libs (from around half a year ago ?) but all basic mixpanel fns works.

**Comment by VictorSnow** [comment]
@samzilverberg  thanks, we are using 2.3.5, enough for our situation.

**Comment by samzilverberg** [comment]
@VictorSnow checkout latest version 4.0.0

I reverted back to including mixpanel source, so should have less deps = less probs.
and it has newer ios/android libs :)
