### ISSUE TITLE
Any plans to support latest sdks ?

### ISSUE THREAD

**Issue by ThomasKientz** [samzilverberg/cordova-mixpanel-plugin#78]
Hi !

Current versions support by the plugins are :
 - iOS: 3.2.0
 - Android: 5.1.4

Current versions released by Mixpanel are :
 - iOS: 3.2.3
 - Android: 5.2.1

Thanks for maintaining this great repo :)

**Comment by samzilverberg** [comment]
of course ;)
i update usually every couple of months, sometimes more often if theres a critical bug update in the updated versions.
I'll try and find time to do it this week.

**Comment by ThomasKientz** [comment]
There is no rush ;) Thanks, you rock !

**Comment by Ferdev** [comment]
Hi!

We're having an issue related to this plugin, and actually it's a bug in the mixpanel-iphone library, which has been fixed in the latest version of the sdk (3.2.3). You can check the original issue here:

https://github.com/mixpanel/mixpanel-iphone/issues/722

The crash message says: `NSInternalInconsistencyException: SwizzlerAssert: Cannot find method for application:didReceiveRemoteNotification:fetchCompletionHandler: on FirebasePlugin` and it happens randomly to some of my users when opening branch links if the app is completely closed.

I would be more than happy to send a pull request myself but I don't know the process you follow to copy the sdk files to the src/ios/mixpanel folder... A mini-guide to illustrate how to update the sdk files would be helpful... Do you just git clone the git tag of the desired version and then copy the files? Or do you use cocoapods or carthage?

And, by the way, **thank you very much**  for your work on this plugin 👍 🙇

**Comment by samzilverberg** [comment]
👍 lets update asap. i will try to do this tomorrow morning (europe time).

FYI i just copy over the mixpanel src files and then use `node src/ios/assetsHelper.js` to generate the lines needed for plugin.xml, simple and stupid.
I tried cocoapods for dep management but it caused too many probs for the plugin users so went back to just including the source files ;)

**Comment by Ferdev** [comment]
That's awesome! Thank you so much! We're planning to release a new version of the app before Christmas, so this is awesome news for us. Thanks!

**Comment by samzilverberg** [comment]
4.1.0 release moments ago with latest android and ios sdks.
I'm on a new computer and not everything is installed here yet so I couldn't try to build via xcode and do a sanity test.

according to the diff it looks like it should work though.
@Ferdev give it a try and let me know.

**Comment by Ferdev** [comment]
Thank you @samzilverberg ! Sure! I'll let you know. I'll try to reproduce the bug with this new version, hopefull this will fix it.

Have a great weekend! 👍

**Comment by Ferdev** [comment]
Hey @samzilverberg, sorry it took me so long to get back to you! We just tested the new plugin version in our production env and the crash we had is completely gone. Thank you so much for the updated! 

Keep the good work!
