### ISSUE TITLE
Track not associated to ID in android

### ISSUE THREAD

**Issue by soupman99** [samzilverberg/cordova-mixpanel-plugin#8]
When I create a track after I've identified someone the tracking events don't show up in the user's track history.  The tracked item DOES show up in the segmentation data though.  Only an issue on android, works as expected on iOS.  Could this be an SDK issue?
    
    mixpanel.people.identify(ionic.Platform.device().uuid)
    mixpanel.track('Account Created', {'Account Type':'Paid'});

**Comment by samzilverberg** [comment]
looks to me like it should work actually.

3 things you could try so we have more knowledge about the issue:
- use peopleIdentify(...) - [android sdk docu](https://mixpanel.com/help/reference/android#creating_profiles) 
- check that ```ionic.Platform.device().uuid``` is actually returning something (not undefined!) on android 
- in mixpanel live data dashboard, check that the $distinct_id for that event is set to the users distinct_id. My guess is that its not, otherwise it should have appeared in the people data as well

**Comment by soupman99** [comment]
mixpanel.people.identify(ionic.Platform.device().uuid)
should have been:
    
    mixpanel.identify(ionic.Platform.device().uuid)

Been staring at the screen too long.

**Comment by samzilverberg** [comment]
lol i've been staring too long as well.
I somehow read it the other way around, that you were using ```mixpanel.identify``` and it was not working for you.

anyway, happy its working for you :+1:
