### ISSUE TITLE
iOS Push Notifications do not work

### ISSUE THREAD

**Issue by jjosef** [samzilverberg/cordova-mixpanel-plugin#85]
This has been an ongoing issue I've tried to get help from Mixpanel about. I cannot get iOS push notifications to work at all even though it says they were sent.

Has anyone had any experience with this?

**Comment by samzilverberg** [comment]
solved already?
for me its always been ios push notifications certificates that gave me trouble, so double and triple check ;)

**Comment by walfridosp** [comment]
Hi @samzilverberg @jjosef I'm also having problems with Push Notifications on iOS, I tetra checked :D and still didn't get it working. From Firebase console using the APNs Certificates works fine, so I don't think there is an issue with that, have you tried it from your side?

**Comment by samzilverberg** [comment]
@walfridosp haven't tried it, but since no one else using the plugin is complaining i'm guessing its something with your project setup (or code) thats missing.

someone posted not lng ago about some minimal firebase vesion thats needed.
this info is now in the README in troubleshooting section. check it out, maybe you have the same problem?
